In [ ]:
# require gradient on a variable 

In [1]:
import torch
from torch.autograd import Variable

In [2]:
x = torch.randn(3)
x = Variable(x, requires_grad=True)
print(x)

tensor([ 0.9463, -0.7820, -0.5577], requires_grad=True)


In [3]:
y = x * 2


In [4]:
while y.data.norm() < 1000:
    y = y * 2
print(y)

tensor([ 969.0587, -800.7357, -571.0603], grad_fn=<MulBackward0>)


In [5]:
gradients = torch.FloatTensor([0.1, 1.0, 0.0001])
y.backward(gradients)

In [6]:
print(x.grad)

tensor([1.0240e+02, 1.0240e+03, 1.0240e-01])


In [6]:
# Fronzen parameters 

In [7]:
from torch import nn, optim
import torchvision

In [8]:
import ssl
ssl._create_default_https_context = ssl._create_unverified_context

In [9]:
model = torchvision.models.resnet18(pretrained=True)

Downloading: "https://download.pytorch.org/models/resnet18-f37072fd.pth" to C:\Users\ASUS/.cache\torch\hub\checkpoints\resnet18-f37072fd.pth
100.0%


In [10]:
# Freeze all the parameters in the network
for param in model.parameters():
    param.requires_grad = False

In [ ]:
## assume a  new data set  with 10 labels 
# in resnet , classifier  is the last linear layer that is model.fc that is the last layer 

In [11]:
model.fc = nn.Linear(512, 10)

In [14]:
##all the parameters in this model , except for the parameters for model.fc  , are frozen 
# the only parameters that compute gradients are weights and bias of model.fc
# notice that although we register  al the parameters  in the optimizer . the only parameters 
## that are computing gradients  and hence updating in gradient descent , are the weights and biases in the classifier 
# the same exclusionaruy functionality is available as a  context manager in torch.no_grad

In [15]:
# Optimize only the classifier
optimizer = optim.SGD(model.parameters(), lr=1e-2, momentum=0.9)

In [16]:
print(optimizer)

SGD (
Parameter Group 0
    dampening: 0
    lr: 0.01
    maximize: False
    momentum: 0.9
    nesterov: False
    weight_decay: 0
)
