In [1]:
import torch

In [2]:
a=[[11,12,13],[21,22,23],[31,32,33]]

In [3]:
A=torch.tensor(a)

In [4]:
A

tensor([[11, 12, 13],
        [21, 22, 23],
        [31, 32, 33]])

# use ndimension , to get number of dimension of a torch tensor   or rank of  a tensor

In [6]:
A.ndimension()

2

# shape attribite of atensor retins the number of rows and columns 

In [8]:
A.shape

torch.Size([3, 3])

# number of elements used in the torch tensor 

In [9]:
A.numel()

9

# indexing  and slicing in 2D

In [11]:
A

tensor([[11, 12, 13],
        [21, 22, 23],
        [31, 32, 33]])

In [10]:
A[1][2]

tensor(23)

In [12]:
A[0,0:2]

tensor([11, 12])

In [13]:
A[1,0:2]

tensor([21, 22])

In [14]:
A[1:3,2]

tensor([23, 33])

In [16]:
A[1:2,1]

tensor([22])

# addition of 2 tensors

In [17]:
X=torch.tensor([[1,0],[0,1]])

In [18]:
Y=torch.tensor([[2,1],[1,2]])

In [19]:
Z=X+Y

In [20]:
Z

tensor([[3, 1],
        [1, 3]])

In [21]:
Z1=2*Y

In [23]:
Y

tensor([[2, 1],
        [1, 2]])

In [22]:
Z1

tensor([[4, 2],
        [2, 4]])

# hamdard product or dot product

In [24]:
Z2=X*Y

In [25]:
Z2

tensor([[2, 0],
        [0, 2]])

## matrix multiplication

In [26]:
A=torch.tensor([[0,1,1],[1,0,1]])
B=torch.tensor([[1,1],[1,1],[-1,1]])

In [29]:
A , B 

(tensor([[0, 1, 1],
         [1, 0, 1]]),
 tensor([[ 1,  1],
         [ 1,  1],
         [-1,  1]]))

In [27]:
C=torch.mm(A,B)

In [28]:
C

tensor([[0, 2],
        [0, 2]])

## finding drivative of a  quadratic function

In [10]:
x=torch.tensor(2)#,requires_grad=True)

In [11]:
x

tensor(2)

In [12]:
y=x**2

In [13]:
y

tensor(4)

## to calculate the derivative 

In [18]:
z=y.backward

In [19]:
z

<bound method Tensor.backward of tensor(4)>

In [23]:
z1=x.grad()

TypeError: 'NoneType' object is not callable

In [22]:
z1.

AttributeError: 'NoneType' object has no attribute 'value'

### 1 .HOW TO BUILD A DATA SET OBJECT  CLASS AND OBJECT 
## 2. how to build a data set transform
## 3. how to compose transforms

In [25]:
from torch.utils.data import Dataset

In [31]:
x=torch.ones(6,1)
x

tensor([[1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.]])

## build a  class

In [33]:
class toy_set(Dataset):
    def __init__(self,length =100 , transform=None):
        self.x=2*torch.ones(length,2)
        self.y=torch.ones(length,1)
        ## stores the number of samples in attribute length 
        self.len=length
        self.transform=transform
        
        
    def __getitem__(self,index):
        sample=self.x[index],self.y[index]
        if self.transform:
                sample=self.transform(sample)
        return sample
    
    
    def __len__(self):
        return self.len

In [34]:
dataset=toy_set()

In [35]:
dataset

In [36]:
dataset[0]

(tensor([2., 2.]), tensor([1.]))

In [37]:
len(dataset)## it will overrde 

100

# daatset object behaves like a list , square bracket []  acts like  the method get_item

In [39]:
dataset[2]## this means x[2],y[2]

(tensor([2., 2.]), tensor([1.]))

## iterate the dataset object 

In [41]:
for i in  range(3):
    x,y=dataset[i]
    print(i,'x:',x,'y:',y)

0 x: tensor([2., 2.]) y: tensor([1.])
1 x: tensor([2., 2.]) y: tensor([1.])
2 x: tensor([2., 2.]) y: tensor([1.])
